### ISSUE TITLE
Add to ethics

### ISSUE THREAD

**Issue by HugoMillwood** [parski/thesis#8]
Ethics: "Därför behöver ni ha med referens till vetensksrådets webbaserade dokument för etiska aspekter. Var också tydligare med hur ni hanterar samtyckandekrav, mm mm som ni hittar på deras hemsida.  Ha också med kopia på hur det medgivandeformulär som ni visade undersökningsdeltagarna i appendix till manuskriptet."

**Comment by HugoMillwood** [comment]
Created this "medgivandeformulär". Should probably be re-written to be more aligned with vetensksrådets webbaserade dokument för etiska aspekter

https://docs.google.com/document/d/1Dq2TF6uwvW8Z8g8nRqNiqVxCI3i76sfIx46GnDUAGUg/edit?usp=sharing

**Comment by parski** [comment]
Rewriting this.

**Comment by parski** [comment]
@HugoMillwood What do you think about the current document? I've rewritten it to make it clearer and added some stuff. Also lies. Lies are okay.

**Comment by HugoMillwood** [comment]
:+1:
